### ISSUE TITLE
cell-click triggering event; coloring certain cells

### ISSUE THREAD

**Issue by meir-retter** [oscar6echo/ezaggrid#1]
Hello Oscar,

First of all, thank you so much for your work on this; AG Grid is great and it's great to be able to use it with Python. I'm currently using it to make a pivot table, and I'm trying to 

- have a cell trigger an event when clicked
- have any cell whose value satisfies a certain property (i.e. contains a string longer than 10 characters) be colored red. (I've seen the example with even/odd being red/blue, and the example where a pivot option is gold, but have not been able to translate from that.)

Are these possible using ezaggrid?

Thank you so much,
Meir Retter

**Comment by oscar6echo** [comment]
First I would like to clarify that **ezaggrid** is as transparent a wrapper to the **aggrid JS lib** as possible.  
Consequently when using ag-grid I advise to search the [official ag-grid documentation](https://www.ag-grid.com/javascript-grid-features/) for examples. It is very very well done - with live (plunker) examples you can start from to build your prototypes. But that means you must be reasonably proficient in JS/CSS, not just Python. There is no intention to hide JS code config from the user with a proprietary layer, on the contrary, transparency means **ezaggrid** is more likely to work with future versions of **ag-grid JS lib**.

I'll take your points in reverse order:
+ To style a cell depending on its value, see this [page](https://www.ag-grid.com/javascript-grid-cell-styles/) in the doc. You mention my example with the even/odd values being red/blue in the notebook [demo_ezaggrid_compress_data](https://nbviewer.jupyter.org/github/oscar6echo/ezaggrid/blob/master/notebooks/demo_ezaggrid_compress_data.ipynb). The key variables are `css_rules` and `ccf`. I would (1) redefine the css classes with relevant names (e.g. `background-white`,  `background-blue`) and the `background-color` CSS property, and (2) change the function selecting the class to check the length of the string e.g. `return params.value.toString().length > MYLIMIT ? 'my-class-red' : 'my-class-white';`.

+ A cell can trigger an event, but that event will stay within the javascript and there is no channel to propagate it back to Python. This is a strong limitation of this very simple `ez*` type of Python package (I've done it with several js libraries, [ezhc](https://github.com/oscar6echo/ezhc), [ezvis3d](https://github.com/oscar6echo/ezvis3d)) which writes js from Python and sends it to the browser which in turns displays it as it would any regular web page. This is why we are working on **ipyaggrid**, an [ipywidget](https://ipywidgets.readthedocs.io/en/latest/) that will enable bi-directional communication Python-Javascript. For more info on ipywidgets, I recommend this [article](https://blog.jupyter.org/authoring-custom-jupyter-widgets-2884a462e724). We hope to have published a first version of **ipyaggrid** within a month.

Hope this helps.
Rgds

**Comment by oscar6echo** [comment]
As mentioned earlier, ipyaggrid is available. See the links in the README.  
Closing the issue
